add_newline = true 

# A minimal left prompt
format = """
$env_var\
$os\
$username\
$hostname\
$directory\
$fill\
$all\
$line_break\
\
$character(fg:greydimmed)"""

palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """
[$localip]($style)"""
command_timeout = 1000

[character]
success_symbol = "[╰⎯](fg:surface2)"
error_symbol = "[╰⎯](fg:red)"
# ╭╴ ╰─

[env_var]
symbol = "╭╴"
variable = 'SHELL'
format = "[$symbol](fg:surface2)"
disabled = false

[os]
format = '[](fg:subtext1)[$symbol ](fg:crust bg:subtext1)[](fg:subtext1)'   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

# Shows current directory
[directory]
truncation_length = 2
truncation_symbol = ' '
home_symbol = " ~/"
read_only_style = ''
read_only = '󱧵 '
format = '[-](fg:surface2)[](fg:pink)[󰷏 ](fg:base bg:pink)[](fg:pink bg:overlay2)[ $read_only$truncation_symbol$path](fg:crust bg:overlay2)[](fg:overlay2)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'
"Documents" = "󰈙"

[git_branch]
# format =  '[$symbol$branch(:$remote_branch)]($style)'
format = "[-](fg:surface2)[](fg:green)[$symbol](fg:base bg:green)[](fg:green bg:overlay0)[ $branch(:remote_branch)](fg:crust bg:overlay0)"
symbol = ""

[git_status]
format = '[ $all_status$ahead_behind](fg:surface1 bg:overlay0)[](fg:overlay0)'

[package]
format = "[\u2500](fg:surface2)[](fg:maroon)[$symbol](fg:base bg:maroon)[](fg:maroon bg:overlay0)[ $version](fg:crust bg:overlay0)[](fg:overlay0)"
symbol = "󰏗"

[cmd_duration]
min_time = 500
format = "[\u2500](fg:surface2)[](fg:yellow)[ ](fg:base bg:yellow)[](fg:yellow bg:overlay0)[ $duration](fg:crust bg:overlay0)[](fg:overlay0)"

[nodejs]
format = "[\u2500](fg:surface2)[](fg:green)[$symbol](fg:base bg:green)[](fg:green bg:overlay0)[ $version](fg:crust bg:overlay0)[](fg:overlay0)"

[elixir]
format = "[\u2500](fg:surface2)[](fg:sapphire)[$symbol](fg:base bg:sapphire)[](fg:sapphire bg:overlay0)[ $version](fg:crust bg:overlay0)[](fg:overlay0)"
symbol = ""

[php]
format = "[\u2500](fg:surface2)[](fg:lavender)[$symbol](fg:base bg:lavender)[](fg:lavender bg:overlay0)[ $version](fg:crust bg:overlay0)[](fg:overlay0)"

[python]
format = "[\u2500](fg:surface2)[](fg:mauve)[$symbol](fg:base bg:mauve)[](fg:mauve bg:overlay0)[ $version](fg:crust bg:overlay0)[](fg:overlay0)"

[docker_context]
disabled = true

[fill]
style = 'fg:surface2'
symbol = "\u2500" # "\u2500" "─" # no line: ' '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
